---
# Cleared - Data De-identification Framework
#
# This Taskfile provides commands for:
# - Environment setup and dependency management
# - Code quality (linting, formatting, testing)
# - Development workflow (watching, cleaning)
# - Documentation and deployment
#
# QUICK START:
#   1. task install-os-deps    # Install Poetry and pre-commit (first time only)
#   2. task setup-env          # Setup Python environment with dependencies
#   3. task verify-env         # Verify everything is working correctly
#   4. task test               # Run tests to ensure everything works
#
# PREREQUISITES:
#   - Python 3.10+ installed
#   - Git repository cloned
#   - Terminal/command line access
#
# COMMON WORKFLOWS:
#   Development: task watch     # Auto-run lint/format/test on file changes
#   Testing:     task test      # Run all tests
#   Cleanup:     task clean     # Remove build artifacts and cache files
#   Help:        task help      # Show all available tasks
#
# For detailed documentation, see README.md

version: '3'

vars:
  PROJECT_DIR_NAME: '{{.CLI_DIR}}'

tasks:

  show:
    desc: >
      Display current Python environment info, Poetry config, and Python version.
      Useful for debugging environment issues.
    cmds:
      - task: verify-deps
      - echo 'Current environment:'
      - poetry env info
      - poetry run python -V

  install-os-deps:
    desc: >
      Install OS dependencies (Poetry and pre-commit) for Ubuntu and macOS.
      Run this FIRST if you don't have Poetry installed. Supports interactive installation.
    cmds:
      - ./scripts/install_os_deps.sh

  install:
    desc: >
      Install only build dependencies (without dev dependencies).
      Use this for production deployments. Depends on verify-deps.
    cmds:
      - task: verify-deps
      - echo 'Installing build dependencies...'
      - poetry install --only main
      - echo 'Build dependencies installed!'

  setup-env:
    desc: >
      Setup complete Python development environment with Poetry.
      Installs all dependencies and configures pre-commit hooks.
      Run this after install-os-deps.
    cmds:
      - task: verify-deps
      - echo 'Setting up Python environment with Poetry...'
      - poetry install --with dev
      - echo 'Configuring pre-commit hooks...'
      - poetry run pre-commit install --hook-type pre-commit --hook-type pre-push
      - echo 'Environment setup complete!'
      - echo 'You can now run task show'

  setup-env-ci:
    desc: >
      Setup Python development environment for CI (without verification).
      Installs all dependencies without checking for OS-level tools.
      Use this in CI workflows where OS dependencies are installed separately.
    cmds:
      - echo 'Setting up Python environment with Poetry (CI mode)...'
      - poetry install --with dev
      - echo 'Python environment setup complete!'

  verify-deps:
    desc: >
      Verify required dependencies are installed (private task).
      Mode: 'dev' (default) checks all dependencies, 'build' only checks task and poetry.
      Usage: task verify-deps -- [dev|build]
    internal: true
    cmds:
      - ./scripts/verify_deps.sh {{.CLI_ARGS}}

  verify-env:
    desc: >
      Verify if setup-env has been executed and environment is ready.
      Checks Python env, cleared package, pre-commit, and git hooks.
      Use this to debug environment issues.
    cmds:
      - ./scripts/verify_env.sh

  verify-env-silent:
    desc: >
      Verify environment silently (internal task).
      Same as verify-env but with no output. Used by other tasks for dependency checking.
    internal: true
    cmds:
      - ./scripts/verify_env.sh silent

  help:
    desc: >
      Show all available tasks with descriptions.
      Use this to discover what commands are available.
    cmds:
      - task --list
  
  lint:
    desc: >
      Run all linters (ruff, yamllint, actionlint). Checks for code quality issues, 
      style violations, and potential bugs.
      Run this before committing code.
    cmds:
      - echo "Running Python code linter (ruff)..."
      - poetry run ruff check
      - echo "Running YAML linter (yamllint)..."
      - poetry run yamllint .
      - echo "Running GitHub Actions linter (actionlint)..."
      - poetry run actionlint .github/workflows/*.yml

  lint-fix:
    desc: >
      Auto-fix linting issues using ruff, yamllint, and actionlint. 
      Automatically corrects many code style and quality issues.
      Run this after lint to fix auto-fixable issues.
    cmds:
      - echo "Auto-fixing Python code issues (ruff)..."
      - poetry run ruff check --fix
      - echo "Auto-fixing YAML issues (yamllint)..."
      - poetry run yamllint .
      - echo "Checking GitHub Actions workflows (actionlint)..."
      - poetry run actionlint .github/workflows/*.yml

  format:
    desc: >
      Format code using ruff (black-like style). Ensures consistent code formatting across the project.
      Run this before committing code.
    cmds:
      - poetry run ruff format

  format-check:
    desc: >
      Check code formatting without modifying files (CI-friendly).
      Fails if code is not properly formatted. Use this in CI pipelines.
    cmds:
      - poetry run ruff format --check

  test:
    desc: >
      Run all tests using pytest with coverage reporting.
      Executes the full test suite and generates coverage reports. Essential before deploying.
    cmds:
      - poetry run pytest

  test-coverage:
    desc: >
      Run tests with coverage reporting and generate HTML report.
      Generates coverage data and HTML report in htmlcov/. Use test-coverage-report to view.
    cmds:
      - echo "Running tests with coverage..."
      - poetry run pytest --cov=cleared --cov-report=html --cov-report=term
      - echo "Coverage report generated in htmlcov/index.html"

  test-coverage-report:
    desc: >
      Open the HTML coverage report in your default browser.
      Requires test-coverage to be run first.
    cmds:
      - |
        if [ -f "htmlcov/index.html" ]; then
          URL="htmlcov/index.html"
          xdg-open $URL || sensible-browser $URL || x-www-browser $URL || gnome-open $URL || open $URL
        else
          echo "Coverage report not found. Run 'task test-coverage' first."
          exit 1
        fi

  type-check:
    desc: >
      Run code quality checks that may catch type-related issues using ruff.
      Note: For full static type checking with mypy, add mypy to dev dependencies.
      This task runs ruff checks which catch some type-related patterns.
    cmds:
      - echo "Running code quality checks (ruff)..."
      - poetry run ruff check

  docs:
    desc: >
      Build and open project documentation using MkDocs.
      Generates HTML documentation and opens it in your default browser (skips opening in CI).
    cmds:
      - echo 'building documentation ...'
      - poetry run mkdocs build
      - |
        if [ -z "$CI" ]; then
          URL="site/index.html"
          xdg-open $URL || sensible-browser $URL || x-www-browser $URL || gnome-open $URL || open $URL
        else
          echo "Documentation built successfully at site/index.html (CI environment detected, skipping browser opening)"
        fi

  docs-serve:
    desc: >
      Serve documentation locally with auto-reload on file changes.
      Starts MkDocs development server. Access at http://127.0.0.1:8000. Press Ctrl+C to stop.
    cmds:
      - echo 'Starting documentation server...'
      - echo 'Documentation will be available at http://127.0.0.1:8000'
      - poetry run mkdocs serve

  clean:
    desc: >
      Clean build artifacts, cache files, and temporary files.
      Removes .pyc files, __pycache__, build directories, and Poetry cache.
      Safe to run anytime.
    cmds:
      - ./scripts/clean.sh

  build:
    desc: >
      Build distribution packages (wheel and source distribution).
      Creates dist/ directory with built packages. Run before publishing to PyPI.
    cmds:
      - task: verify-deps build
      - echo "Building distribution packages..."
      - poetry build
      - echo "Build complete! Packages are in dist/"

  deps-outdated:
    desc: >
      List outdated dependencies in the project.
      Shows which packages have newer versions available.
    cmds:
      - task: verify-deps
      - echo "Checking for outdated dependencies..."
      - poetry show --outdated || echo "All dependencies are up to date"

  deps-update:
    desc: >
      Update all dependencies to their latest compatible versions.
      Updates poetry.lock file. Review changes before committing.
    cmds:
      - task: verify-deps
      - echo "Updating dependencies..."
      - poetry update
      - echo "Dependencies updated! Review poetry.lock before committing."

  version-show:
    desc: >
      Display the current project version.
      Reads version from VERSION file and pyproject.toml.
    cmds:
      - echo "Current version from VERSION file:"
      - cat VERSION
      - echo ""
      - echo "Current version from pyproject.toml:"
      - poetry version --short

  version-bump:
    desc: >
      Bump the project version (major, minor, or patch).
      Usage: task version-bump -- [major|minor|patch] or task version-bump BUMP_TYPE=[major|minor|patch].
             Updates both VERSION file and pyproject.toml.
    vars:
      BUMP_TYPE: "{{.CLI_ARGS}}"
    cmds:
      - |
        if [ -z "{{.BUMP_TYPE}}" ]; then
          echo "Usage: task version-bump -- [major|minor|patch]"
          echo "Example: task version-bump -- patch"
          exit 1
        fi
        if [ "{{.BUMP_TYPE}}" != "major" ] && [ "{{.BUMP_TYPE}}" != "minor" ] && [ "{{.BUMP_TYPE}}" != "patch" ]; then
          echo "Error: Bump type must be 'major', 'minor', or 'patch'"
          exit 1
        fi
        echo "Bumping version ({{.BUMP_TYPE}})..."
        poetry version {{.BUMP_TYPE}}
        NEW_VERSION=$(poetry version --short)
        echo "$NEW_VERSION" > VERSION
        echo "Version bumped to: $NEW_VERSION"

  changelog:
    desc: >
      Generate changelog using gitchangelog.
      Creates CHANGELOG.md from git commit history. Requires gitchangelog to be installed.
    cmds:
      - task: verify-deps
      - echo "Generating changelog..."
      - poetry run gitchangelog > CHANGELOG.md || echo "Changelog generation completed (or no changes to log)"
      - echo "Changelog written to CHANGELOG.md"

  ci-local:
    desc: >
      Run the full CI pipeline locally (simulate CI environment).
      Runs lint, format-check, type-check, test, and docs build. Use this before pushing.
    cmds:
      - task: verify-deps
      - task: verify-env-silent
      - |
        echo "========================================="
        echo "Running local CI pipeline..."
        echo "========================================="
        echo ""
        echo "Step 1/5: Running linter..."
        task lint
        echo ""
        echo "Step 2/5: Checking code formatting..."
        task format-check
        echo ""
        echo "Step 3/5: Running type checks..."
        task type-check
        echo ""
        echo "Step 4/5: Running tests..."
        task test
        echo ""
        echo "Step 5/5: Building documentation..."
        CI=true task docs
        echo ""
        echo "========================================="
        echo "✅ All CI checks passed!"
        echo "========================================="

  install-jupyter:
    desc: >
      Install Jupyter kernel for the cleared project.
      Sets up a custom kernel named 'cleared' for use in Jupyter notebooks. One-time setup.
    cmds:
      - poetry run python -m ipykernel install --user --name "cleared" --display-name "Cleared"
      - echo 'Jupyter kernel installed successfully!'
      - echo 'To configure Jupyter server, run poetry run jupyter server --generate-config'
      - echo 'To set a password, run poetry run jupyter server password'

  run-jupyter:
    desc: >
      Start Jupyter Lab server for remote access.
      Configures and starts Jupyter with remote access capabilities. Requires password setup first.
    cmds:
      - . scripts/run_jupyter_remote.sh

  watch:
    desc: >
      Watch Python files for changes and auto-run lint, format, test.
      Monitors .py files and runs quality checks automatically. Press Ctrl+C to stop.
    cmds:
      - task: verify-deps
      - task: verify-env-silent
      - ./scripts/watch.sh
